{{ $zkServers := "" }}
{{ $zkServerSuffix := printf "%s-zk" ( include "apache-ignite.fullname" .) }}

{{ $rootCtx := . }}

{{ range until ( .Values.zookeeper.replicas | int ) }}
  {{ $zkServerHost := printf "%s-zk-%d.%s" ( include "apache-ignite.fullname" $rootCtx ) . $zkServerSuffix }}
  {{ $zkServer := printf "%s:%d2888:%d3888" $zkServerHost (add . 2) (add . 2) }}
  {{ $zkServers = printf "%s;%s" $zkServers $zkServer }}
{{ end }}

{{ $zkServersLen := ( $zkServers | len ) | int }}
{{ $zkServers = $zkServers | substr 1 $zkServersLen }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "apache-ignite.fullname" . }}-zk
  labels:
    {{- include "apache-ignite.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "apache-ignite.fullname" . }}-zk
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      {{- include "apache-ignite.selectorLabelsZk" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apache-ignite.selectorLabelsZk" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-zk
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "32181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_SERVERS
              value: {{ $zkServers }}
          command: ["bash"]
          args:
            - -c
            - "export ZK_HOSTNAME_VALUE=$(hostname) && export ZOOKEEPER_SERVER_ID=$((${ZK_HOSTNAME_VALUE:0-1}+1)) && echo My server id is: ${ZOOKEEPER_SERVER_ID} && /etc/confluent/docker/run"
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
